//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GHUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GHUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to document.addEventListener(&apos;click&apos;, function (event) {
        ///    const elem = event.target;
        ///    const returnObject =
        ///    {
        ///        type: &apos;click&apos;,
        ///        targetId: elem.id,
        ///        targetName: elem.name,
        ///        targetType: elem.type,
        ///        targetValue: elem.value,
        ///        targetTagName: elem.tagName
        ///    };
        ///    //console.log(returnObject);
        ///    window.chrome.webview.postMessage(returnObject);
        ///});
        ///
        ///document.addEventListener(&apos;keydown&apos;, function (event) {
        ///    const returnObject =
        ///    {
        ///        type [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AddDocumentClickListener {
            get {
                return ResourceManager.GetString("AddDocumentClickListener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap button {
            get {
                object obj = ResourceManager.GetObject("button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap div {
            get {
                object obj = ResourceManager.GetObject("div", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap label {
            get {
                object obj = ResourceManager.GetObject("label", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function queryInputElements() {
        ///    const returnObjects = [];
        ///    const inputElements = document.getElementsByTagName(&apos;input&apos;);
        ///
        ///    for (const c of inputElements) {
        ///        const inputData = new Object();
        ///
        ///        inputData.id = c.id;
        ///        inputData.value = c.value;
        ///        inputData.name = c.name;
        ///        inputData.max = c.max;
        ///        inputData.min = c.min;
        ///        inputData.isChecked = c.checked;
        ///        inputData.type = c.type;
        ///        returnObjects.push(inputData);
        ///    }
        ///    return  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string QueryInputElementsInDOM {
            get {
                return ResourceManager.GetString("QueryInputElementsInDOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap slider {
            get {
                object obj = ResourceManager.GetObject("slider", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap web_window {
            get {
                object obj = ResourceManager.GetObject("web_window", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
